### PR TITLE
FIX: On windows, holding down two keys at the exact same time causes sound to repeat

### LINKED ISSUE #278: On windows, holding down two keys at the exact same time causes sound to repeat
This issue may also be present on linux, but it's not present on macOS.

### PR DESCRIPTION
**Pull request by NotLazy**
Fixes #278

### CODE REVIEW

**Comment by talalnas1r** [comment]
hey, just wanna clear up, is this issue same as holding two keys will play both at the same time ?

**Review by vlad1202alekseev-byte — COMMENTED** [review]
ироирироиито

File: src/app.js [hunk 1]
```diff
@@ -409,19 +409,31 @@ function packsToOptions(packs, pack_list) {
       }
     });
 
+    // store pressed state of multiple keys
+    let pressed_keys = {};
```
Comment (vlad1202alekseev-byte) [inline src/app.js:413]: вывыфвфвыфвв
